const 1950s = 

1952: {11: {"day":14,"title":"here in my heart","artist":"al martino","wks at no.1":9} },
1953: {01: {"day":16,"title":"you belong to me","artist":"jo stafford","wks at no.1":1} }
,{01: {"day":23,"title":"comes a-long a-love","artist":"kay starr","wks at no.1":1} },
,{01: {"day":30,"title":"outside of heaven","artist":"eddie fisher","wks at no.1":1} },
,{02: {"day":06,"title":"don't let the stars get in your eyes","artist":"perry como with the ramblers","wks at no.1":5} },
,{03: {"day":13,"title":"she wears red feathers","artist":"guy mitchell","wks at no.1":4} },
,{04: {"day":10,"title":"broken wings","artist":"stargazers","wks at no.1":1} },
,{04: {"day":17,"title":"(how much is) that doggie in the window","artist":"lita roza","wks at no.1":1} },
,{04: {"day":24,"title":"i believe","artist":"frankie laine","wks at no.1":9} },
,{06: {"day":26,"title":"i'm walking behind you","artist":"eddie fisher with sally sweetland","wks at no.1":1} },
,{07: {"day":03,"title":"i believe","artist":"frankie laine","wks at no.1":6} },
,{08: {"day":14,"title":"the song from moulin rouge","artist":"mantovani","wks at no.1":1} },
,{08: {"day":21,"title":"i believe","artist":"frankie laine","wks at no.1":3} },
,{09: {"day":11,"title":"look at that girl","artist":"guy mitchell","wks at no.1":6} },
,{10: {"day":23,"title":"hey joe","artist":"frankie laine","wks at no.1":2} },
,{11: {"day":06,"title":"answer me","artist":"david whitfield","wks at no.1":1} },
,{11: {"day":13,"title":"answer me","artist":"frankie laine","wks at no.1":8} },
,{12: {"day":11,"title":"answer me","artist":"david whitfield","wks at no.1":1} },
1954 {01: {"day":08,"title":"oh mein papa","artist":"eddie calvert","wks at no.1":9} },
, {03: {"day":12,"title":"i see the moon","artist":"stargazers","wks at no.1":5} },
, {04: {"day":16,"title":"secret love","artist":"doris day","wks at no.1":1} },
, {04: {"day":23,"title":"i see the moon","artist":"stargazers","wks at no.1":1} },
, {04: {"day":30,"title":"such a night","artist":"johnnie ray","wks at no.1":1} },
, {05: {"day":08,"title":"secret love","artist":"doris day","wks at no.1":8} },
, {07: {"day":02,"title":"cara mia","artist":"david whitfield, with chorus and mantovani and his orchestra","wks at no.1":
, {09: {"day":10,"title":"little things mean a lot","artist":"kitty kallen","wks at no.1":1} },
, {09: {"day":17,"title":"three coins in the fountain","artist":"frank sinatra","wks at no.1":3} },
, {10: {"day":08,"title":"hold my hand","artist":"don cornell","wks at no.1":4} },
, {11: {"day":05,"title":"my son my son","artist":"vera lynn","wks at no.1":2} },
, {11: {"day":19,"title":"hold my hand","artist":"don cornell","wks at no.1":1} },
, {11: {"day":26,"title":"this ole house","artist":"rosemary clooney","wks at no.1":1} },
, {12: {"day":03,"title":"let's have another party","artist":"winifred atwell","wks at no.1":5} },
1955 {01: {"day":07,"title":"finger of suspicion","artist":"dickie valentine with the stargazers","wks at no.1":1} },
, {01: {"day":14,"title":"mambo italiano","artist":"rosemary clooney with the mellomen","wks at no.1":1} },
, {01: {"day":21,"title":"finger of suspicion","artist":"dickie valentine with the stargazers","wks at no.1":2} },
, {02: {"day":04,"title":"mambo italiano","artist":"rosemary clooney with the mellomen","wks at no.1":2} },
, {02: {"day":18,"title":"softly, softly","artist":"ruby murray","wks at no.1":3} },
, {03: {"day":11,"title":"give me your word","artist":"tennessee ernie ford","wks at no.1":7} },
, {04: {"day":29,"title":"cherry pink and apple blossom white","artist":"perez 'prez' prado  his orchestra, the king of th
, {05: {"day":13,"title":"stranger in paradise","artist":"tony bennett","wks at no.1":2} },
, {05: {"day":27,"title":"cherry pink and apple blossom white","artist":"eddie calvert","wks at no.1":4} },
, {06: {"day":24,"title":"unchained melody","artist":"jimmy young","wks at no.1":3} },
, {07: {"day":15,"title":"dreamboat","artist":"alma cogan","wks at no.1":2} },
, {07: {"day":29,"title":"rose marie","artist":"slim whitman","wks at no.1":11} },
, {10: {"day":14,"title":"the man from laramie","artist":"jimmy young","wks at no.1":4} },
, {11: {"day":11,"title":"hernando's hideaway","artist":"johnston brothers","wks at no.1":2} },
, {11: {"day":25,"title":"rock around the clock","artist":"bill haley  his comets","wks at no.1":3} },
, {12: {"day":16,"title":"christmas alphabet","artist":"dickie valentine","wks at no.1":3} },
1956 {01: {"day":06,"title":"rock around the clock","artist":"bill haley  his comets","wks at no.1":3} },
, {01: {"day":20,"title":"sixteen tons","artist":"tennessee ernie ford","wks at no.1":2} },
, {02: {"day":17,"title":"memories are made of this","artist":"dean martin","wks at no.1":4} },
, {03: {"day":16,"title":"it's almost tomorrow","artist":"dream weavers","wks at no.1":2} },
, {03: {"day":30,"title":"rock and roll waltz","artist":"kay starr","wks at no.1":2} },
, {04: {"day":06,"title":"it's almost tomorrow","artist":"dream weavers","wks at no.1":1} },
, {04: {"day":13,"title":"poor people of paris","artist":"winifred atwell","wks at no.1":3} },
, {05: {"day":04,"title":"no other love","artist":"ronnie hilton","wks at no.1":6} },
, {06: {"day":15,"title":"i'll be home","artist":"pat boone","wks at no.1":5} },
, {07: {"day":20,"title":"why do fools fall in love","artist":"teenagers  frankie lymon","wks at no.1":3} },
, {08: {"day":10,"title":"whatever will be will be","artist":"doris day","wks at no.1":6} },
, {09: {"day":21,"title":"lay down your arms","artist":"anne shelton","wks at no.1":4} },
, {10: {"day":19,"title":"a woman in love","artist":"frankie laine","wks at no.1":4} },
, {11: {"day":16,"title":"just walkin' in the rain","artist":"johnnie ray","wks at no.1":7} },
1957 {01: {"day":04,"title":"singing the blues","artist":"guy mitchell","wks at no.1":1} },
, {01: {"day":11,"title":"singing the blues","artist":"tommy steele  the steelmen","wks at no.1":1} },
, {01: {"day":18,"title":"singing the blues","artist":"guy mitchell","wks at no.1":1} },
, {01: {"day":25,"title":"the garden of eden","artist":"frankie vaughan","wks at no.1":4} },
, {02: {"day":01,"title":"singing the blues","artist":"guy mitchell","wks at no.1":1} },
, {02: {"day":22,"title":"young love","artist":"tab hunter","wks at no.1":7} },
, {04: {"day":12,"title":"cumberland gap","artist":"lonnie donegan","wks at no.1":5} },
, {05: {"day":17,"title":"rock-a-billy","artist":"guy mitchell","wks at no.1":1} },
, {05: {"day":24,"title":"butterfly","artist":"andy williams","wks at no.1":2} },
, {06: {"day":07,"title":"yes tonight josephine","artist":"johnnie ray","wks at no.1":3} },
, {06: {"day":28,"title":"gamblin' man/putting on the style","artist":"lonnie donegan","wks at no.1":2} },
, {07: {"day":12,"title":"all shook up","artist":"elvis presley with the jordanaires","wks at no.1":7} },
, {08: {"day":30,"title":"diana","artist":"paul anka","wks at no.1":9} },
, {11: {"day":01,"title":"that'll be the day","artist":"crickets","wks at no.1":3} },
, {11: {"day":22,"title":"mary's boy child","artist":"harry belafonte","wks at no.1":7} },
1958 {01: {"day":10,"title":"great balls of fire","artist":"jerry lee lewis","wks at no.1":2} },
, {01: {"day":24,"title":"jailhouse rock","artist":"elvis presley","wks at no.1":3} },
, {02: {"day":14,"title":"the story of my life","artist":"michael holliday","wks at no.1":2} },
, {02: {"day":28,"title":"magic moments","artist":"perry como","wks at no.1":8} },
, {04: {"day":25,"title":"whole lotta woman","artist":"marvin rainwater","wks at no.1":3} },
, {05: {"day":16,"title":"who's sorry now","artist":"connie francis","wks at no.1":6} },
, {06: {"day":27,"title":"on the street where you live","artist":"vic damone","wks at no.1":2} },
, {07: {"day":04,"title":"all i have to do is dream/claudette","artist":"everly brothers","wks at no.1":7} },
, {08: {"day":22,"title":"when","artist":"kalin twins","wks at no.1":5} },
, {09: {"day":26,"title":"carolina moon/stupid cupid","artist":"connie francis","wks at no.1":6} },
, {11: {"day":07,"title":"it's all in the game","artist":"tommy edwards","wks at no.1":3} },
, {11: {"day":28,"title":"hoots mon","artist":"lord rockingham's xi","wks at no.1":3} },
, {12: {"day":19,"title":"it's only make believe","artist":"conway twitty","wks at no.1":5} },
1959 {01: {"day":23,"title":"the days the rains came","artist":"jane morgan","wks at no.1":1} },
, {01: {"day":30,"title":"one night/i got stung","artist":"elvis presley","wks at no.1":3} },
, {02: {"day":20,"title":"as i love you","artist":"shirley bassey","wks at no.1":4} },
, {03: {"day":20,"title":"smoke gets in your eyes","artist":"platters","wks at no.1":1} },
, {03: {"day":27,"title":"side saddle","artist":"russ conway","wks at no.1":4} },
, {04: {"day":24,"title":"it doesn't matter anymore","artist":"buddy holly","wks at no.1":3} },
, {05: {"day":15,"title":"a fool such as i/i need your love tonight","artist":"elvis presley","wks at no.1":5} },
, {06: {"day":19,"title":"roulette","artist":"russ conway","wks at no.1":2} },
, {07: {"day":03,"title":"dream lover","artist":"bobby darin","wks at no.1":4} },
, {07: {"day":31,"title":"living doll","artist":"cliff richard  the shadows","wks at no.1":6} },
, {09: {"day":11,"title":"only sixteen","artist":"craig douglas","wks at no.1":4} },
, {10: {"day":09,"title":"here comes summer","artist":"jerry keller","wks at no.1":1} },
, {10: {"day":16,"title":"mack the knife","artist":"bobby darin","wks at no.1":2} },
, {10: {"day":30,"title":"travellin' light","artist":"cliff richard  the shadows","wks at no.1":5} },
, {12: {"day":04,"title":"what do you want","artist":"adam faith","wks at no.1":3} },
, {12: {"day":18,"title":"what do you want to make those eyes at me for","artist":"emile ford  the checkmates","wks at no.
1960: {01: {"day":29,"title":"starry eyed","artist":"michael holliday with the michael sammes singers","wks at no.1":1} },